# Setup
title:               tpflug
tagline:             ' [tobi, human, engineer]'
description:         "I'm a Germany based Software Engineer and Consultant who loves to work with people and solve problems"
url:                 https://www.tpflug.me
baseurl:
paginate:            100
permalink:           pretty

# About/contact
author:
  name:              Tobias Pflug
  url:               https://twitter.com/tpflug
  email:             tobias.pflug@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
